---
- hosts: 127.0.0.1
  gather_facts: no
  
  tasks:
  - name: send email with the report attached
    mail: 
      subject: 마포 애경타워 스위치 백업 파일
      body: 참고
      attach: /var/lib/awx/projects/_11__ljw90/backup/{ lookup('pipe', 'date +%Y%m%d') }}/config.zip
      host: spam.aekyung.kr
      port: 25
      sender: jungwoo.lee@aekyung.kr
      recipients: 
      - jungwoo.lee@aekyung.kr
      - jhchoi4452@aekyung.kr
      - seungjoon.lee@aekyung.kr
      - holay@aekyung.kr
      
    run_once: true
