---
- hosts: 127.0.0.1
  gather_facts: no
  
  tasks:
  - name: send email with the report attached
    mail: 
      subject:  스위치 헬스체크 
      body: 참고
      attach: /var/lib/awx/projects/_11__ljw90/junifer.xlsx
      host: spam.aekyung.kr
      port: 25
      sender: jungwoo.lee@aekyung.kr
      recipients: 
      - jungwoo.lee@aekyung.kr
      - jhchoi4452@aekyung.kr 
      
      
      
    run_once: true
