---
- name: CISCO switch check
  hosts: log
  connection: 127.0.0.1
  gather_facts: no
# strategy: free

  tasks:
    - name: name
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | awk '{sub(/,.*/, ""); print}'| grep "NAME:" | awk '{print $2,$3}'
      ignore_errors: True
      register: NAME

    - name: serial
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | grep "SN:" | awk '{print $8,$9}'
      ignore_errors: True
      register: Serial

    - name: pid
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | awk '{sub(/,.*/, ""); print}'| grep "PID:" | awk '{print $2}'
      ignore_errors: True
      register: PID

      
    - name: Make Result Directory
      local_action:
        module: file
        path: "/var/lib/awx/projects/_11__ljw90/Result/{{ lookup('pipe', 'date +%Y%m%d') }}"
        state: directory
        mode: u=rwX,g=rX,o=rX

    - name: Result summary
      local_action:
        copy content= "{{ NAME.stdout}}|{{ Serial.stdout }}|{{ PID.stdout }}"
        dest="/var/lib/awx/projects/_11__ljw90/Result/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt"

    - name: Assemble from fragments from a directory
      assemble:
        src: "/var/lib/awx/projects/_11__ljw90/Result/{{ lookup('pipe', 'date +%Y%m%d') }}"
        dest: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
      ignore_errors: True

    - name: Result modify1
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "', 'failed': False, 'changed': False}"
        replace: ""

    - name: Result modify1
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "'msg': u'"
        replace: ""

    - name: Result modify1
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "{'msg': '"
        replace: ""

    - name: Result modify1
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "{'msg': '"
        replace: ""

    - name: Result modify2
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "'failed': False, 'changed': False"
        replace: ""

    - name: Result modify3
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "',"
        replace: ""

    - name: Result modify4
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "{"
        replace: ""

    - name: Result modify5
      replace:
        path: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
        regexp: "}"
        replace: ""

    - name: To excel
      shell: python3 /var/lib/awx/projects/_11__ljw90/333.py
