---
- name: CISCO switch check
  hosts: log
  connection: 127.0.0.1
  gather_facts: no
# strategy: free

  tasks:
    - name: name
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/20240429/MPIS_L3#2.txt | awk 'BEGIN{FS="NAME:"} {print $2}' | awk '{sub(/,.*/, ""); print}'
      ignore_errors: True
      register: Name

    - name: serial
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/20240429/MPIS_L3#2.txt | awk 'BEGIN{FS="SN:"} {print $2}'
      ignore_errors: True
      register: SN

    - name: pid
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/20240429/MPIS_L3#2.txt | awk 'BEGIN{FS="PID:"} {print $2}' | awk '{sub(/,.*/, ""); print}'
      ignore_errors: True
      register: Pid

   
    - name: Make Result Directory
      local_action:
        module: file
        path: "/var/lib/awx/projects/_11__ljw90/Result/{{ lookup('pipe', 'date +%Y%m%d') }}"
        state: directory
        mode: u=rwX,g=rX,o=rX

    - name: Result summary
      local_action:
        copy content="{{ Name.stdout }}____{{ SN.stdout }}____{{ Pid.stdout }}"
        dest="/var/lib/awx/projects/_11__ljw90/Result/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt"

    - name: Assemble from fragments from a directory
      assemble:
        src: "/var/lib/awx/projects/_11__ljw90/Result/{{ lookup('pipe', 'date +%Y%m%d') }}"
        dest: "/var/lib/awx/projects/_11__ljw90/Result/cisco.log"
      ignore_errors: True

    - name: To excel
      shell: python3 /var/lib/awx/projects/_11__ljw90/333.py

