---
- name: CISCO switch check
  hosts: log
  connection: 127.0.0.1
  gather_facts: no
# strategy: free

  tasks:
    - name: modify2
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | tr ',NAME' '\nNAME'
      ignore_errors: True
      register: result

    - name: show_backup2
      local_action:
        copy content="{{ result.stdout }}"
        dest=/var/lib/awx/projects/_11__ljw90/backup/{{ inventory_hostname }}_2

    - name: modify3
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | sed -e 's/^ *//g' -e 's/ *$//g'  | sed 's/^$/!/g'
      ignore_errors: True
      register: result2

    - name: show_backup3
      local_action:
        copy content="{{ result2.stdout }}"
        dest=/var/lib/awx/projects/_11__ljw90/backup/{{ inventory_hostname }}_2

    - name: modify4
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | sed 's/\r$//'
      ignore_errors: True
      register: result4

    - name: show_backup3
      local_action:
        copy content="{{ result4.stdout }}"
        dest=/var/lib/awx/projects/_11__ljw90/backup/{{ inventory_hostname }}_2

    - name: modify4
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | sed -e 's/^ *//g' -e 's/ *$//g' | sed 's/^$/!/g' | sed 's/^M/!/g'
      ignore_errors: True
      register: result5

    - name: show_backup3
      local_action:
        copy content="{{ result5.stdout }}"
        dest=/var/lib/awx/projects/_11__ljw90/backup/{{ inventory_hostname }}_2

    - name: modify4
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | sed -n '/^NAME/,/\n/p' | tr '\r' ' ' | tr '\n' ',' | sed 's/\!/\n/g'
      ignore_errors: True
      register: result6

    - name: show_backup3
      local_action:
        copy content="{{ result6.stdout }}"
        dest=/var/lib/awx/projects/_11__ljw90/backup/{{ inventory_hostname }}_2

    - name: modify4
      shell: cat /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt | sed -n '/,NAME:/,/NAME:/p'
      ignore_errors: True
      register: result7

    - name: Make Result Directory
      local_action:
        module: file
        path: "/var/lib/awx/projects/_11__ljw90/Result"
        state: directory
        mode: u=rwX,g=rX,o=rX

    - name: csv
      copy:
        content: "{{ inventory_hostname }}|{{ result7.stdout }}"
        dest: /var/lib/awx/projects/_11__ljw90/Result/{{inventory_hostname}}.csv

    - name: Assemble Result Summary
      assemble:
        src: "/var/lib/awx/projects/_11__ljw90"
        dest: "/var/lib/awx/projects/_11__ljw90/Result/result.csv"

    - name: show_Result
      shell: python3 /var/lib/awx/projects/_11__ljw90/555.py
