---
- name: cisco
  hosts: ios
  gather_facts: no
  connection: localhost
  collections: requirements.yml


  tasks:
    - name: show_output
      ios_command:
        commands:
          - terminal length 0
          - show run
          - show version
          - show processes cpu
          - show processes memory
          - show env all
          - show interfaces status err-disabled
          - show interfaces | in up|CRC
          - show interfaces status
          - show interfaces counters errors          
          - show logging
                 
      register: show
