---
- name: conpress test
  gather_facts: no
  hosts: localhost
  connection: 127.0.0.1
  
  tasks:
    - name: Make Result Directory
      become: yes
      archive:
        path: /var/lib/awx/projects/_11__ljw90/backup/*
        dest: /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}.zip
        format: zip
     
