---
- name: juniper
  hosts: all
  gather_facts: no
  connection: localhost


  tasks:
    - name: show_output
      junos_command:
      connection: netconf
        commands:
          - show version
          - show chassis hardware
          - show chassis routing-engine
          - show chassis environment
          - show system alarm
          - show interfaces extensive
          - show log messages
          
                 
      register: show


