---
- name: juniper
  hosts: all
  gather_facts: no
  connection: localhost

  tasks:                
    - name: Make Result Directory
      local_action:
        module: file
        path: "/var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}"
        state: directory
        mode: u=rwX,g=rX,o=rX   


    - name: show_backup
      junos_config:
        backup: yes
        backup_options:
         lines:
          - show version
          - show chassis hardware
          - show chassis routing-engine
          - show chassis environment
          - show system alarm
          - show interfaces extensive
         filename: /var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.log
         dir_path: /var/lib/awx/projects/_11__ljw90/backup/
       

