---
- name: juniper
  hosts: all
  gather_facts: no
  connection: localhost

  tasks:
    - name: show_output
      junos_command:
        commands:
          - show version
          - show chassis hardware
          
