---
- name: juniper
  hosts: all
  gather_facts: no
  connection: localhost

  tasks:
    - name: show_output
      junos_command:
        commands:
          - show version
          - show chassis hardware
          - show chassis routing-engine
          - show chassis environment
          - show system alarm
          - show interfaces extensive
          - show log messages
          
                 
      register: show

 
    - name: Make Result Directory
      local_action:
        module: file
        path: "/var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}"
        state: directory
        mode: u=rwX,g=rX,o=rX

    - name: show_backup
      local_action:
        copy content="\n\nshow version\n\n{{ show.stdout[1] }}\n\nshow chassis hardware\n\n{{ show.stdout[2] }}\n\nshow chassis routing-engine\n\n{{ show.stdout[3] }}\n\nshow chassis environment\n\n{{ show.stdout[4] }}\n\nshow system alarm\n\n{{ show.stdout[5] }}\n\nshow interfaces extensive\n\n{{ show.stdout[6] }}\n\nshow log messages\n\n{{ show.stdout[7] }}"
        dest=/var/lib/awx/projects/_11__ljw90/backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt

