---
- name: conpress test
  gather_facts: no
  hosts: all
  connection: 127.0.0.1
  
  tasks:
    - name: Make Result Directory
      become: yes
      archive:
        path: /var/lib/awx/projects/_11__ljw90/backup/*
        dest: /var/lib/awx/projects/_11__ljw90/backup/config.zip
        format: zip
     
    - name: send email with the report attached
      mail:
      subject: "Report of ClamAV compliance"
      body: 
        attach: /var/lib/awx/projects/_11__ljw90/backup/config.zip
        from: junwoo.lee@aekyung.kr
        to:
        - jungwoo.lee@aekyung.kr
        - jhchoi4452@aekyung.kr
        - seungjoon.lee@aekyung.kr
        - holay@aekyung.kr
    run_once: true
